package com.example.backend.model;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5.1
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.02.01 at 03:08:59 PM CET
//

import javax.xml.bind.annotation.XmlRegistry;

@XmlRegistry
public class ObjectFactory {

    public ObjectFactory() {
    }

    public ZahtevZaAutorskaPrava createZahtevZaAutorskaPrava() {
        return new ZahtevZaAutorskaPrava();
    }

    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    public TLice createTLice() {
        return new TLice();
    }

    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    public SadrzajZahteva createSadrzajZahteva() {
        return new SadrzajZahteva();
    }

    public AutorskoDelo createAutorskoDelo() {
        return new AutorskoDelo();
    }

    public InformacijeOZahtevu createInformacijeOZahtevu() {
        return new InformacijeOZahtevu();
    }

    public OsnovniLicniPodaci createOsnovniLicniPodaci() {
        return new OsnovniLicniPodaci();
    }

    public PodnosilacZahteva createPodnosilacZahteva() {
        return new PodnosilacZahteva();
    }

    public Autor createTAutor() {
        return new Autor();
    }

    public ZasnivanoDelo createZasnivanoDelo() {
        return new ZasnivanoDelo();
    }

    public PodaciOAutoru createAutor() {
        return new PodaciOAutoru();
    }

    public Adresa createAdresa() {
        return new Adresa();
    }
}

